module.exports = {
    addParent: Symbol('addParent'),
    collections: Symbol('collections'),
    collectionsMap: Symbol('collectionsMap'),
    connections: Symbol('connections'),
    deferreds: Symbol('deferreds'),
    domains: Symbol('domains'),
    externalId: Symbol('externalId'),
    externalCaller: Symbol('externalCaller'),
    immediates: Symbol('immediates'),
    intervals: Symbol('intervals'),
    init: Symbol('init'),
    map: Symbol('map'),
    namespace: Symbol('namespace'),
    parents: Symbol('parents'),
    promises: Symbol('promises'),
    removeParent: Symbol('removeParent'),
    saveQueue: Symbol('saveQueue'),
    startSaveCycle: Symbol('startSaveCycle'),
    store: Symbol('store'),
    timeouts: Symbol('timeouts'),
    virtualStore: Symbol('virtualStore')
};