module.exports = {
    addParent: Symbol('addParent'),
    collections: Symbol('collectionsProps'),
    deferreds: Symbol('deferreds'),
    domains: Symbol('domains'),
    immediates: Symbol('immediates'),
    intervals: Symbol('intervals'),
    init: Symbol('init'),
    parents: Symbol('parents'),
    promises: Symbol('promises'),
    removeParent: Symbol('removeParent'),
    saveQueue: Symbol('saveQueue'),
    startSaveCycle: Symbol('startSaveCycle'),
    store: Symbol('store'),
    timeouts: Symbol('timeouts'),
};